name: Deploy Script

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
        shell: bash

  BuildDependencies:
    needs: UnitTesting
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
        shell: bash

  DeployPPD:
    needs: BuildDependencies
    uses: ./.github/workflows/template.yml
  DeployProd:
    needs: DeployPPD
    uses: ./.github/workflows/template.yml
