name: Deploy Script

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      changes_in_specific_folder: ${{ steps.filter.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@v2
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            changes_in_specific_folder:
              - 'nextjs/**/*'
          


  BuildNextJs_DEV:
    needs: check_changes
    if: ${{needs.check_changes.outputs.changes_in_specific_folder}} == 'true'
    uses: ./.github/workflows/nextjsStuff.yml
    with:
      environment: Dev

  BuildBackend_DEV:
    needs: BuildNextJs_DEV
    if: always()
    uses: ./.github/workflows/backendStuff.yml
    with:
      environment: Dev


  # BuildNextJs_NP:
  #   needs: [check_changes,BuildBackend_DEV]
  #   if: needs.check_changes.outputs.changes_in_specific_folder == 'true'
  #   uses: ./.github/workflows/nextjsStuff.yml
  #   with:
  #     environment: np

  # BuildBackend_NP:
  #   needs: [check_changes,BuildNextJs_NP]
  #   if: always()
  #   uses: ./.github/workflows/backendStuff.yml
  #   with:
  #     environment: np

  # BuildNextJs_Prod:
  #   needs: [check_changes,BuildBackend_NP]
  #   if: needs.check_changes.outputs.changes_in_specific_folder == 'true'
  #   uses: ./.github/workflows/nextjsStuff.yml
  #   with:
  #     environment: prod

  # BuildBackend_prod:
  #   needs:  [check_changes,BuildNextJs_Prod]
  #   if: always()
  #   uses: ./.github/workflows/backendStuff.yml
  #   with:
  #     environment: prod

