name: Deploy Script

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
        shell: bash

  Build:
    needs: UnitTesting
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
        shell: bash

  DeployPPD:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
      - name: Run build script
        run: echo "fake build"
        shell: bash


  IntegrationTesting:
    needs: [Templates, References, Glue, App, Docker, Batches, Pipelines]
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
        shell: bash

  AcceptanceTesting:
    needs: [IntegrationTesting]
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
        shell: bash
