name: Deploy Script

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
        shell: bash

  BuildDependencies:
    needs: UnitTesting
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
        shell: bash

  BuildImages:
    needs: UnitTesting
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
        shell: bash

  PPD:
    needs: [BuildDependencies,BuildImages]
    uses: ./.github/workflows/templateppd.yml
  Production:
    needs: PPD
    uses: ./.github/workflows/template.yml
