name: Deploy Script

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.changes_detected }}
    steps:
      - uses: actions/checkout@v3
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            changes_detected:
              - 'nextjs/**/*'
              
          
  BuildNextJs_DEV:
    needs: check_changes
    if:  ${{ needs.check_changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/nextjsStuff.yml
    with:
      environment: Dev

  BuildBackend_DEV:
    needs: check_changes
    if: always()
    uses: ./.github/workflows/backendStuff.yml
    with:
      environment: Dev


  BuildNextJs_NP:
    needs: [BuildBackend_DEV,BuildNextJs_DEV]
    if: ${{ needs.check_changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/nextjsStuff.yml
    with:
      environment: np

  BuildBackend_NP:
    needs: [BuildBackend_DEV,BuildNextJs_DEV]
    if: always()
    uses: ./.github/workflows/backendStuff.yml
    with:
      environment: np

  BuildNextJs_Prod:
    needs: [BuildBackend_NP,BuildNextJs_NP]
    if: ${{ needs.check_changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/nextjsStuff.yml
    with:
      environment: np

  BuildBackend_Prod:
    needs: [BuildBackend_NP,BuildNextJs_NP]
    if: always()
    uses: ./.github/workflows/backendStuff.yml
    with:
      environment: np