name: Deploy Script

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  UnitTesting:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
        shell: bash

  BuildDependencies:
    needs: UnitTesting
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
        shell: bash

  BuildImages:
    needs: UnitTesting
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: echo "fake build"
        shell: bash

  PPD:
    needs: [BuildDependencies,BuildImages]
    uses: ./.github/workflows/templateppd.yml
  Integration+AcceptanceTesting:
    needs: [PPD,BuildImages]
    runs-on: ubuntu-latest
    environment: 
      name: ppd
    steps:
      - id: step1
        run: sleep 2
      - id: step23
        run: sleep 2
  Production:
    needs: PPD
    uses: ./.github/workflows/template.yml

  Prod/Integration+AcceptanceTesting:
    needs: [PPD,Integration+AcceptanceTesting,Production]
    runs-on: ubuntu-latest
    environment: 
      name: prod
    steps:
      - id: step1
        run: sleep 2
      - id: step23
        run: sleep 2
