name: Deploy Script

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deployPPD:
    environment: ppd
      uses: ./.github/workflows/template.yml
  deployProd:
    needs: BaseInfra
    environment: production
      uses: ./.github/workflows/template.yml
