
name: CI/CD
on:
  push:
  pull_request:
  schedule:
    - cron: '0 14 3 * *' # Monthly at 2pm on the 3rd
jobs:
  test:
    name: 🐘 PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pg: [15, 14, 13, 12, 11, 10, 9.6, 9.5, 9.4, 9.3, 9.2, 9.1, '9.0', 8.4, 8.3, 8.2]
    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: docker build -t pgxn-tools-test .
      - name: Test as root
        run: "docker run --rm --mount \"type=bind,src=$(pwd)/test,dst=/repo\" pgxn-tools-test /repo/runtest.sh ${{ matrix.pg }}"
      - name: Test as non-root
        run: "docker run --rm --mount \"type=bind,src=$(pwd)/test,dst=/repo\" -e AS_USER=worker pgxn-tools-test /repo/runtest.sh ${{ matrix.pg }}"
  publish:
    # Publish for a tag starting with v.
    name: Push to Docker Hub
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: pgxn/pgxn-tools
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=raw,value=bookworm
          labels: |
            org.opencontainers.image.title=PGXN Tools
            org.opencontainers.image.licenses=PostgreSQL
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push
        # https://github.com/marketplace/actions/build-and-push-docker-images
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}