name: Deploy Script

on:
  workflow_call:

permissions:
  contents: read

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - id: step1
        run: sleep 2
      - id: step23
        run: sleep 2
      - id: step12222
        run: sleep 3
      - id: step231
        run: sleep 5 
      - id: step113
        run: sleep 5
      - id: step132
        run: sleep 5
